name: CitadelPluginTest
version: '${project.version}'
main: edolce.citadelplugin.CitadelPluginTest
depend:
  - Factions
commands:
  assault:
    description: Open gui for assaults
    usage: /assault
